# Generated by Django 3.2.8 on 2022-10-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(default='', max_length=500, verbose_name='分析的URL地址')),
                ('high', models.IntegerField(default=0, verbose_name='高危漏洞')),
                ('middle', models.IntegerField(default=0, verbose_name='中危漏洞')),
                ('low', models.IntegerField(default=0, verbose_name='低危漏洞')),
                ('type', models.CharField(default='', max_length=50, verbose_name='扫描类型')),
                ('status', models.CharField(default='', max_length=500, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='扫描时间')),
            ],
            options={
                'db_table': 'analysis_url',
            },
        ),
        migrations.CreateModel(
            name='Vulnerabilities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(default='', max_length=500, verbose_name='具体的分析的URL地址')),
                ('leak_name', models.CharField(default='', max_length=500, verbose_name='漏洞名字')),
                ('type', models.CharField(default='低危漏洞', max_length=50, verbose_name='漏洞类别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='扫描时间')),
                ('tags', models.CharField(default='', max_length=255, verbose_name='漏洞标签')),
                ('status', models.CharField(default='', max_length=255, verbose_name='漏洞状态')),
                ('affects_detail', models.CharField(default='', max_length=255, verbose_name='临界细节')),
            ],
            options={
                'db_table': 'vulnerabilities',
            },
        ),
    ]
