# Generated by Django 3.2.8 on 2022-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisurl',
            name='scan_id',
            field=models.CharField(default='', max_length=500, verbose_name='漏洞编号'),
        ),
        migrations.AddField(
            model_name='vulnerabilities',
            name='scan_id',
            field=models.CharField(default='', max_length=500, verbose_name='所属编号'),
        ),
    ]
