# Generated by Django 3.2.8 on 2022-10-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221003_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Middleware_vuln',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('result', models.CharField(max_length=100, null=True)),
                ('CVE_id', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
    ]
